const useStyles = (theme: any) => ({
  pageWrapper: {
    height: "100vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background:
      "url(/images/flyo-data-storage-component/bg-desktop.png),hsl(229, 57%, 11%) ",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "0 100%",
    backgroundSize: "100% 50%",
    [theme.breakpoints.down("md")]: {
      background:
        "url(/images/flyo-data-storage-component/bg-mobile.png),hsl(229, 57%, 11%) ",
      backgroundRepeat: "no-repeat",
      backgroundPosition: "0 100%",
      backgroundSize: "100% 100%",
    },
  },
  contentWrapper: {
    display: "flex",
    alignItems: "flex-end",
    [theme.breakpoints.down("md")]: {
      flexDirection: "column",
      alignItems: "center",
      width: "95%",
    },
  },
  leftCard: {
    backgroundColor: "hsl(228, 56%, 26%)",
    padding: theme.spacing(4),
    width: "300px",
    borderRadius: theme.spacing(1, 12, 1, 1),
    marginRight: theme.spacing(3),
    [theme.breakpoints.down("md")]: {
      width: "95%",
      marginRight: 0,
      marginBottom: theme.spacing(2),
    },
  },
  iconsWrapper: {
    display: "flex",
    alignItems: "center",
    marginTop: theme.spacing(3),
  },
  iconWrapper: {
    backgroundColor: "hsl(229, 57%, 11%)",
    padding: theme.spacing(1),
    width: "40px",
    height: "40px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: theme.spacing(1),
    marginRight: theme.spacing(1.5),
  },
  rightCard: {
    backgroundColor: "hsl(228, 56%, 26%)",
    padding: theme.spacing(3, 4),
    width: "600px",
    borderRadius: theme.spacing(1),
    [theme.breakpoints.down("md")]: {
      width: "95%",
      marginBottom: theme.spacing(2),
      padding: theme.spacing(4),
    },
  },
  headingText: {
    fontFamily: "Raleway, sans-serif",
    fontSize: "14px",
    fontWeight: 400,
    color: "hsl(243, 100%, 93%)",
  },
  storageSpan: {
    fontFamily: "Raleway, sans-serif",
    fontSize: "14px",
    fontWeight: 700,
    color: "hsl(243, 100%, 93%)",
  },
  progressBar: {
    backgroundColor: "hsl(229, 57%, 11%)",
    borderRadius: "25px",
    height: "20px",
    padding: theme.spacing(0.1),
    marginTop: theme.spacing(1.5),
    display: "flex",
    alignItems: "center",
    position: "relative",
  },
  progressIndicator: {
    backgroundImage:
      "linear-gradient(to right, hsl(6, 100%, 80%), hsl(335, 100%, 65%))",
    borderRadius: "25px",
    height: "16px",
    width: "81.5%",
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
  },
  endCircle: {
    borderRadius: "100%",
    backgroundColor: "#FFFFFF",
    width: "13px",
    marginRight: theme.spacing(0.3),
    height: "13px",
  },
  storageBox: {
    position: "absolute",
    top: -110,
    right: 0,
    backgroundColor: "#FFFFFF",
    borderRadius: theme.spacing(1, 1, 0, 1),
    padding: theme.spacing(1, 3),
    "&::after": {
      content: `" "`,
      position: "absolute",
      bottom: "-15px",
      right: 0,
      margin: theme.spacing(0, "auto"),
      width: 0,
      height: 0,
      borderTop: "15px solid  #FFFFFF",
      borderLeft: "15px solid transparent",
      borderRight: "15px solid #FFFFFF",
      borderBottom: "15px solid transparent",
    },
    [theme.breakpoints.down("md")]: {
      top: 95,
      left: "50%",
      borderRadius: theme.spacing(1),
      transform: "translate(-50%,-50%)",
      padding: theme.spacing(1),
      width: "150px",
      textAlign: "center",
      "&::after": {
        content: `" "`,
        position: "absolute",
        bottom: "-15px",
        right: 0,
        margin: theme.spacing(0, "auto"),
        width: 0,
        height: 0,
        borderTop: "15px solid  transparent",
        borderLeft: "15px solid transparent",
        borderRight: "15px solid transparent",
        borderBottom: "15px solid transparent",
      },
    },
  },
  storageLeftText: {
    fontFamily: "Raleway, sans-serif",
    fontSize: "32px",
    fontWeight: 700,
    color: "#000000",
    marginRight: theme.spacing(1),
  },
  gbLeftText: {
    fontFamily: "Raleway, sans-serif",
    fontSize: "14px",
    fontWeight: 700,
    color: "hsl(229, 7%, 55%)",
  },
  markersWrapper: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: theme.spacing(0.5),
  },
  marker: {
    fontFamily: "Raleway, sans-serif",
    fontSize: "14px",
    fontWeight: 700,
    color: "hsl(243, 100%, 93%)",
  },
});

export default useStyles;
